# Generated by Django 4.2.9 on 2024-01-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monumental_discoveries', '0002_remove_user_address_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('phone_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('enquiry_date', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='state_images'),
        ),
    ]
