# Generated by Django 4.2.9 on 2024-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monumental_discoveries', '0003_enquiry_state_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='state_images'),
        ),
    ]
