# Generated by Django 4.2.9 on 2024-01-27 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monumental_discoveries', '0004_alter_state_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='monumental_discoveries.state'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monuments_cities', to='monumental_discoveries.city'),
        ),
        migrations.AlterField(
            model_name='monuments',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monuments_state', to='monumental_discoveries.state'),
        ),
    ]
