# Generated by Django 4.2.9 on 2024-01-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monumental_discoveries', '0005_alter_city_state_id_alter_monuments_city_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monuments',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
