# Generated by Django 4.2.9 on 2024-01-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monumental_discoveries', '0006_monuments_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monuments',
            name='quote',
        ),
        migrations.AddField(
            model_name='state',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
