# Generated by Django 4.2.9 on 2024-01-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monumental_discoveries', '0007_remove_monuments_quote_state_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monuments',
            name='monument_location',
            field=models.TextField(),
        ),
    ]
